In [2]:
!nvidia-smi

Thu Nov 25 12:01:50 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.44       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P0    27W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
import torch

In [4]:
# Создайте случайный FloatTensor размера 3x4x5

tmp = torch.rand(3, 4, 5).type(torch.float32)

In [5]:
# Выведите его форму (shape)
tmp.shape

torch.Size([3, 4, 5])

In [6]:
# Приведите его к форме 6 X 10
tmp.view(6, 10)

tensor([[0.2212, 0.0072, 0.8941, 0.2481, 0.5784, 0.4422, 0.5063, 0.1188, 0.3367,
         0.6674],
        [0.4818, 0.9115, 0.3568, 0.9282, 0.7558, 0.6373, 0.6123, 0.3889, 0.6802,
         0.8848],
        [0.5179, 0.4069, 0.9458, 0.8620, 0.6596, 0.9875, 0.9674, 0.4822, 0.4828,
         0.9636],
        [0.1058, 0.9038, 0.3997, 0.3788, 0.9744, 0.8902, 0.6983, 0.7708, 0.7519,
         0.3332],
        [0.0410, 0.9124, 0.3187, 0.0676, 0.4771, 0.9376, 0.6073, 0.2736, 0.5871,
         0.9398],
        [0.2830, 0.9753, 0.9960, 0.2637, 0.2366, 0.4041, 0.7133, 0.2134, 0.3772,
         0.5397]])

In [7]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
tmp * torch.DoubleTensor([1, 4, 2, 2, 1])

tensor([[[0.2212, 0.0287, 1.7882, 0.4962, 0.5784],
         [0.4422, 2.0252, 0.2376, 0.6733, 0.6674],
         [0.4818, 3.6460, 0.7135, 1.8563, 0.7558],
         [0.6373, 2.4492, 0.7778, 1.3603, 0.8848]],

        [[0.5179, 1.6275, 1.8916, 1.7240, 0.6596],
         [0.9875, 3.8695, 0.9645, 0.9655, 0.9636],
         [0.1058, 3.6153, 0.7994, 0.7577, 0.9744],
         [0.8902, 2.7932, 1.5417, 1.5039, 0.3332]],

        [[0.0410, 3.6496, 0.6374, 0.1352, 0.4771],
         [0.9376, 2.4292, 0.5472, 1.1742, 0.9398],
         [0.2830, 3.9014, 1.9919, 0.5273, 0.2366],
         [0.4041, 2.8531, 0.4267, 0.7544, 0.5397]]], dtype=torch.float64)

In [8]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
torch.matmul(tmp.view(6, 10), torch.transpose(tmp.view(6, 10), 1, 0))

tensor([[2.2691, 2.5570, 3.3478, 2.3591, 2.1727, 2.2147],
        [2.5570, 4.8008, 4.8467, 4.2065, 3.6952, 3.3156],
        [3.3478, 4.8467, 5.8116, 4.3803, 3.9013, 3.7629],
        [2.3591, 4.2065, 4.3803, 4.6316, 3.6712, 3.1258],
        [2.1727, 3.6952, 3.9013, 3.6712, 3.7187, 2.9488],
        [2.2147, 3.3156, 3.7629, 3.1258, 2.9488, 3.3000]])

In [17]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
from torch.autograd import Variable

x = Variable(torch.FloatTensor([1]), requires_grad = True)
z = Variable(torch.FloatTensor([0.5]), requires_grad = True)
t = Variable(torch.FloatTensor([2]), requires_grad = True)

y = x**3 + z -75*t

In [18]:
y

tensor([-148.5000], grad_fn=<SubBackward0>)

In [20]:
y.backward([x, z, t])

In [21]:
x.grad

tensor([3.])

In [22]:
z.grad

tensor([1.])

In [23]:
t.grad

tensor([-75.])

In [27]:
# Создайте единичный тензор размера 5x6

x = torch.ones((5, 6))

In [29]:
# Переведите его в формат numpy

type(x), type(x.numpy())

(torch.Tensor, numpy.ndarray)

In [31]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5

In [32]:
x = torch.FloatTensor([1])
w = Variable(torch.FloatTensor([1]), requires_grad=True)

y = x ** w -2 * x**2 + 5

In [33]:
from torch import nn 
from torch import optim

In [35]:
x, w, y

(tensor([1.]),
 tensor([1.], requires_grad=True),
 tensor([4.], grad_fn=<AddBackward0>))

In [36]:
optimizer = optim.SGD([w], lr=0.01)
criterion = nn.MSELoss()

In [37]:
lin = nn.Linear(1, 1, bias=False)

In [40]:
optimizer.zero_grad()
x = torch.FloatTensor([100])

pred = x ** lin(torch.FloatTensor([1])) -2 * x**2 + 5
loss = criterion(pred, y)
loss

tensor(3.9996e+08, grad_fn=<MseLossBackward0>)

In [41]:
loss.backward()

In [42]:
optimizer.step()

In [43]:
pred

tensor([-19994.9414], grad_fn=<AddBackward0>)

In [44]:
target = torch.FloatTensor([10])
target

tensor([10.])

In [45]:
lin.weight.grad

tensor([[-10615.7695]])